name: Generate JSDoc documentation
description: Generates documentation for a Javascript project
author: brunokrauss
branding:
  icon: book-open
  color: gray-dark
inputs:
  jsdoc-path:
    description: 'Path to Javascript File'
    required: true
    default: './index.js'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jsdoc-path }}
